config/routes.rb
Rails.application.routes.draw do

  get 'products/new'

  get "log_in" =>"sessions#new", :as =>"log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" =>"sessions#destroy", :as =>"log_out"

  get "newproduct" =>"products#new", :as =>"newproduct"
  
  root :to =>"sessions#new"
  resources :users
  resources :sessions
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
#	attr_accessible :email, :password, :password_confirmation
	attr_accessor :password

#	attr_accessor :email, :password, :password_confirmation
	before_save:encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on=>:create
	validates_presence_of :email
	validates_uniqueness_of :email

	def encrypt_password
		if password.present?
			self.password_hash = password
		end
	end

	def self.authenticate(email,password)
		user = find_by_email(email)
		if user && password == user.password_hash
			user
		else
			nil
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	helper_method :current_user

	private
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(product_params)
	
	@current_user ||= User.find(session[:user_id]) if session[:user_id]

  	@product.email = @current_user.email

  	if @product.save
  		redirect_to root_url, :notice => "Product Create Successfully"
  	else
  		render "new"
  	end
  end

  private
  def product_params
    params.require(:product).permit(:productname,:productdes)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	user = User.authenticate(params[:email],params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url, :notice =>"Logged in!"
  	else
  		flash.now.alert = "Invalid email or password"
  		render "new"
  	end
  end
  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, :notice =>"Logged Out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to root_url, :notice => "Signed up!"
  	else
  		render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth</title>

<!--  <link rel="stylesheet" href="bootstrap.css">	-->
  <%= stylesheet_link_tag "bootstrap" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<div class="nav">
	<div class="container">

		<% if current_user %>
			Logged in as <%= current_user.email %>
			<%= link_to "注销",log_out_path %>
		<% else %>
		<%= link_to "注册",sign_up_path %> or 
		<%= link_to "登陆", log_in_path %>
		<% end %>
	</div>
</div>


<body>
<%= yield %>

</body>
</html>

app/views/products/new.html.erb
<div class ="container">
<h1>New Prodcut</h1>

<%= form_for @product do |f| %>

<p>
	<%= f.label :productname %><br />
	<%= f.text_field :productname %>
</p>

<p>
	<%= f.label :productdes %><br />
	<%= f.text_area :productdes %><br />
</p>

<p class="button"><%= f.submit %></p>

<% end %>
</div>

app/views/users/new.html.erb
	<div class="container">
		<% flash.each do |name,msg| %>
		<%= content_tag :div, msg, :id =>"{flash#{name}}" %>
		<% end %>


<%= form_for @user, :html => {:class =>'form-inline'} do |f| %>
			  <% if @user.errors.any? %>
			    <div class="error_messages">
			      <h2>Form is invalid</h2>
			      <ul>
			        <% for message in @user.errors.full_messages %>
			          <li><%= message %></li>
			        <% end %>
			      </ul>
			    </div>
			  <% end %>


	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</p>

	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</p>

	<p class="button"><%= f.submit %></p>


<% end %>

</div>